name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: "Create comment with API"
        run: |
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            -H `Authorization: Bearer ${GITHUB_TOKEN}`\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${USER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -d '{"body":"pai comment"}'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: ${{ github.event.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
